include: package:mews_pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_relative_imports

analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore

  exclude:
    - "**/di.config.dart"
    - "**/*.gr.dart"
